
[functions.create-user]
enabled = true
verify_jwt = true
import_map = "./functions/create-user/deno.json"
entrypoint = "./functions/create-user/index.ts"

[functions.rpa-proxy]
enabled = true
verify_jwt = false
